
# Specify the services for our docker compose setup
services:
  products_db:
    # specify the image name of our database
    # If the image is not found in our local repository
    # It will be pulled from docker registry that is Docker Hub
    image: postgres:16.12-bookworm
    ports:
      - "5432:5432"
    # Mount a volume to persist postgreSQL data
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:  
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]  
            interval: 10s  
            timeout: 5s  
            retries: 3    
    environment:  # Use environment variables for db configuration
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DATABASE=${DB_NAME}

  api:
    build:
      # path to the directory containing the Dockerfile
      context: .

      # Specify the image name
    image: products_api
    environment:
      - DB_NAME=${DB_NAME}  
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=products_db
      - DB_PORT=${DB_PORT}
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app

    # Map port 8000 on the host to port 8000 on the container
    ports:
      - 8000:8000

    # Define a dependency on the "products_db" service, so it starts first
    depends_on:
      products_db:
        condition: service_healthy
        
  
volumes:
  postgres_data:

